	INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("First Project", "Easy", 500, "1/1", "2/3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Easy Project", "Easy", 10000, "1/1", "2/3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Hard Project", "Hard", 1000, "1/1", "2/3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Project", "Hard", 100, "1/1", "2/3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("A Project", "Fun", 600, "1/1", "2/3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Simple Project", "Music", 200, "1/1", "2/3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Difficult Project", "Hard", 14400, "1/1", "2/3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Fun Project", "Music", 1023400, "1/1", "2/3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Worst Project", "Books", 100, "1/1", "2/3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Best Project", "Books", 20000, "1/1", "2/3");

INSERT INTO users (name, age) VALUES ("Andy", 20);
INSERT INTO users (name, age) VALUES ("Skye", 23);
INSERT INTO users (name, age) VALUES ("Michael", 34);
INSERT INTO users (name, age) VALUES ("Tracy", 60);
INSERT INTO users (name, age) VALUES ("Matt", 19);
INSERT INTO users (name, age) VALUES ("Chase", 37);
INSERT INTO users (name, age) VALUES ("Mason", 40);
INSERT INTO users (name, age) VALUES ("Tim", 24);
INSERT INTO users (name, age) VALUES ("Dan", 28);
INSERT INTO users (name, age) VALUES ("Alex", 22);
INSERT INTO users (name, age) VALUES ("Dhara", 22);
INSERT INTO users (name, age) VALUES ("Pam", 22);
INSERT INTO users (name, age) VALUES ("Jim", 43);
INSERT INTO users (name, age) VALUES ("Layne", 26);
INSERT INTO users (name, age) VALUES ("Jerry", 44);
INSERT INTO users (name, age) VALUES ("Mike", 62);
INSERT INTO users (name, age) VALUES ("Dave", 69);
INSERT INTO users (name, age) VALUES ("Kurt", 27);
INSERT INTO users (name, age) VALUES ("Alan", 80);
INSERT INTO users (name, age) VALUES ("David", 21);

INSERT INTO pledges (user_id, project_id, amount) VALUES (1,1,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (2,2,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (3,3,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4,3,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (5,4,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (6,1,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (7,2,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (8,6,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (9,5,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (10,8,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (11,2,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (12,9,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (13,9,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (14,10,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (15,2,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (16,3,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (17,6,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (18,7,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (19,6,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (20,5,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (14,4,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4,10,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (2,1,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (5,2,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (15,2,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (19,1,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (20,7,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (20,6,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (11,9,200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (12,8,200);