	INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("First Project", "Easy", 500, "1/1", "2/3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Easy Project", "Easy", 10000, "1/1", "2/3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Hard Project", "Hard", 1000, "6/1", "6/3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Project", "Hard", 100, "6/1", "6/3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("A Project", "Fun", 600, "6/1", "6/3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Simple Project", "Tolerable", 200, "6/1", "6/3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Difficult Project", "Hard", 14400, "6/1", "6/3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Fun Project", "Fun", 1023400, "6/1", "6/3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Worst Project", "Hard", 100, "6/1", "6/3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Best Project", "Fun", 20000, "6/1", "6/3");